// Default route data if none is passed
export const DEFAULT_ROUTE = {
  from: 'Downtown Station',
  to: 'Airport Terminal',
  duration: '32 min',
  distance: '5.2 km',
  eco: '8.5',
  ecoColor: '#10B981',
  cost: '₹35',
  modes: ['train', 'bus', 'walk'],
};

export const ROUTE_STEPS = [
  {
    id: '1',
    type: 'walk',
    title: 'Walk to Metro Station',
    duration: '5 min',
    distance: '450m',
    description: 'Head northeast on Main St',
    icon: 'walk',
    iconColor: '#3b82f6',
    iconBg: '#dbeafe',
    cost: 'Free',
    accessibility: true,
    features: ['Free', '♿ Accessible'],
  },
  {
    id: '2',
    type: 'train',
    title: 'Metro Blue Line',
    duration: '18 min',
    stops: '6 stops',
    description: 'Downtown → Central Hub',
    icon: 'train',
    iconColor: '#10b981',
    iconBg: '#d1fae5',
    cost: '₹20',
    accessibility: true,
    busy: true,
    features: ['₹20', '♿ Accessible', '🔥 Busy'],
  },
  {
    id: '3',
    type: 'bus',
    title: 'Express Bus 45',
    duration: '12 min',
    description: 'Direct • Central Hub → Airport',
    icon: 'bus',
    iconColor: '#8b5cf6',
    iconBg: '#ede9fe',
    cost: '₹15',
    accessibility: true,
    electric: true,
    features: ['₹15', '♿ Accessible', '🌱 Electric'],
  },
  {
    id: '4',
    type: 'walk',
    title: 'Walk to Terminal',
    duration: '3 min',
    distance: '200m',
    description: 'Follow signs to Terminal B',
    icon: 'walk',
    iconColor: '#3b82f6',
    iconBg: '#dbeafe',
    cost: 'Free',
    accessibility: true,
    features: ['Free', '♿ Accessible'],
  },
];
